package ru.olmi.dto;

public enum DialogState {
    IDLE,
    WAITING_FOR_WORD,
    WAITING_FOR_WORD_SEARCH,
    WAITING_FOR_USER_TRANSLATION,
    WAITING_FOR_TOPIC,
    WAITING_FOR_IMPORT_FILE,
    WAITING_FOR_LEARNING_TOPIC
}
